language: scala

scala:
- 2.11.11
- 2.12.3

jdk:
- oraclejdk8

before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- du -h -d 4 $HOME/.coursier/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - $HOME/.sbt/cache
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.ivy2

before_install:
- export PATH=${PATH}:./vendor/bundle

install:
- rvm use 2.2.3 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.4.3

script:
- sbt ++$TRAVIS_SCALA_VERSION orgScriptCI
- sbt ++$TRAVIS_SCALA_VERSION tut

after_success:
- sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess
- bash <(curl -s https://codecov.io/bash) -t token_replace-me